services:
  - type: web
    name: cert-quiz
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python quiz_server_cloud.py
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
